In [ ]:
from google.colab import files
uploaded = files.upload()

Saving session4_dummy_students_data.csv.xls to session4_dummy_students_data.csv (2).xls


In [ ]:
import pandas as pd

df = pd.read_csv("session4_dummy_students_data.csv (2).xls")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

Head


In [ ]:
print("First 5 rows (df.head()):")
display(df.head())



First 5 rows (df.head()):


,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82
1,102,Diya,16,Delhi,91,88,94,96,11,10,93
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60
3,104,Meera,16,Noida,72,79,81,89,7,8,78
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45


Tail

In [ ]:

print("\nLast 5 rows (df.tail()):")
display(df.tail())


Last 5 rows (df.tail()):


,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score
15,116,Riya,16,Noida,92,90,96,98,13,10,96
16,117,Om,17,Mumbai,61,69,65,79,6,7,68
17,118,Aditi,16,Delhi,80,85,83,91,9,9,84
18,119,Yash,17,Mathura,43,49,46,66,3,5,48
19,120,Sneha,16,Noida,77,73,80,87,8,8,79


Info

In [ ]:
print("\nDataFrame Info (df.info()):")
df.info()


DataFrame Info (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   student_id             20 non-null     int64 
 1   name                   20 non-null     object
 2   age                    20 non-null     int64 
 3   city                   20 non-null     object
 4   math                   20 non-null     int64 
 5   science                20 non-null     int64 
 6   english                20 non-null     int64 
 7   attendance_percent     20 non-null     int64 
 8   study_hours_per_week   20 non-null     int64 
 9   assignments_submitted  20 non-null     int64 
 10  final_project_score    20 non-null     int64 
dtypes: int64(9), object(2)
memory usage: 1.8+ KB


Average

In [ ]:
sci = df['science'].to_numpy()
math = df['math'].to_numpy()
eng = df['english'].to_numpy()
print((sci.sum() + math.sum() + eng.sum())/3)

1427.0


In [ ]:
science_scores=df['science'].to_numpy()

In [ ]:
science_scores = df["science"].to_numpy()
print(science_scores)
print(type(science_scores))
print(science_scores.max())

[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]
<class 'numpy.ndarray'>
93


In [ ]:
import numpy as np

science_marks = np.array(df['science'])
print(science_marks)

[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]


In [ ]:
math_scores = df['math'].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.max())

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
95


Average of Students

In [ ]:
df['average_score'] = df[['math', 'science', 'english']].mean(axis=1)
print(df[['name', 'math', 'science', 'english', 'average_score']].head())

    name  math  science  english  average_score
0  Aarav    78       84       69      77.000000
1   Diya    91       88       94      91.000000
2  Kabir    55       61       58      58.000000
3  Meera    72       79       81      77.333333
4  Rohan    40       52       47      46.333333


### Filter 1: Top Students (average score > 85)

In [ ]:
top_students = df[df['average_score'] > 85] # Filter students with an average score greater than 85
print('Students with average score greater than 85:')
display(top_students[['name', 'average_score', 'math', 'science', 'english']])

Students with average score greater than 85:


,name,average_score,math,science,english
1,Diya,91.000000,91,88,94
5,Sara,90.333333,88,93,90
7,Ananya,92.000000,95,92,89
13,Priya,88.666667,89,86,91
15,Riya,92.666667,92,90,96


This table shows students who have an `average_score` greater than 85. These are considered the top performing students based on their core subject scores.

### Filter 2: Students with Low Attendance (attendance percent < 75)

In [ ]:
low_attendance_students = df[df['attendance_percent'] < 75] # Filter students with attendance percentage less than 75
print('Students with attendance percent less than 75:')
display(low_attendance_students[['name', 'attendance_percent', 'average_score']])

Students with attendance percent less than 75:


,name,attendance_percent,average_score
4,Rohan,68,46.333333
8,Vivaan,71,52.000000
12,Dev,62,40.666667
18,Yash,66,46.000000


This table lists students with an `attendance_percent` less than 75. These students may require additional attention regarding their attendance.

### Filter 3: Students from Mathura

In [ ]:
mathura_students = df[df['city'] == 'Mathura'] # Filter students whose city is 'Mathura'
print('Students from Mathura:')
display(mathura_students[['name', 'city', 'average_score']])

Students from Mathura:


,name,city,average_score
2,Kabir,Mathura,58.000000
6,Ishaan,Mathura,66.666667
10,Arjun,Mathura,67.333333
14,Kunal,Mathura,57.333333
18,Yash,Mathura,46.000000


# ***`STUDENT ANALYSER`***





### Create 'Result' Column (Pass/Fail)

In [ ]:
# Create 'result' column: Pass if average >= 40, otherwise Fail
df['result'] = df['average_score'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')
print("DataFrame with 'result' column added (first 5 rows):")
display(df[['name', 'average_score', 'result']].head())

DataFrame with 'result' column added (first 5 rows):


,name,average_score,result
0,Aarav,77.000000,Pass
1,Diya,91.000000,Pass
2,Kabir,58.000000,Pass
3,Meera,77.333333,Pass
4,Rohan,46.333333,Pass


### Print Class Average

In [ ]:
# Print overall class average score
class_average = df['average_score'].mean()
print(f"Overall Class Average Score: {class_average:.2f}")

Overall Class Average Score: 71.35


### Print Highest and Lowest Average Scores

In [ ]:
# Print highest and lowest average scores
highest_average = df['average_score'].max()
lowest_average = df['average_score'].min()
print(f"Highest Average Score: {highest_average:.2f}")
print(f"Lowest Average Score: {lowest_average:.2f}")

Highest Average Score: 92.67
Lowest Average Score: 40.67


### Print Top Student(s)

In [ ]:
# Print student(s) with the highest average score
top_students_by_avg = df[df['average_score'] == df['average_score'].max()]
print("Top Student(s) by Average Score:")
display(top_students_by_avg[['name', 'average_score', 'math', 'science', 'english']])

Top Student(s) by Average Score:


,name,average_score,math,science,english
15,Riya,92.666667,92,90,96



Print students with attendance below 75.

In [ ]:
print('Students with attendance percent less than 75:')
display(low_attendance_students[['name', 'attendance_percent', 'average_score']])

Students with attendance percent less than 75:


,name,attendance_percent,average_score
4,Rohan,68,46.333333
8,Vivaan,71,52.000000
12,Dev,62,40.666667
18,Yash,66,46.000000


### Print Students with Fewer Than 6 Assignments Submitted

In [ ]:
# Filter and print students who submitted fewer than 6 assignments
low_assignments_students = df[df['assignments_submitted'] < 6]
print("Students who submitted fewer than 6 assignments:")
display(low_assignments_students[['name', 'assignments_submitted', 'average_score']])

Students who submitted fewer than 6 assignments:


,name,assignments_submitted,average_score
4,Rohan,5,46.333333
12,Dev,4,40.666667
18,Yash,5,46.000000


### Save Final Output

In [ ]:
# Save the final DataFrame to a CSV file
output_filename = 'session4_student_report.csv'
df.to_csv(output_filename, index=False)
print(f"Final student report saved to {output_filename}")

Final student report saved to session4_student_report.csv


## ***`Home Work`***

### Average Final Project Score

In [43]:
average_final_project_score = df['final_project_score'].mean()
print(f"Average Final Project Score: {average_final_project_score:.2f}")

Average Final Project Score: 73.65


### Students with Study Hours Per Week Greater Than 8

In [44]:
high_study_hours_students = df[df['study_hours_per_week'] > 8]
print("Students with study hours per week greater than 8:")
display(high_study_hours_students[['name', 'study_hours_per_week', 'average_score']])

Students with study hours per week greater than 8:


,name,study_hours_per_week,average_score
1,Diya,11,91.000000
5,Sara,10,90.333333
7,Ananya,12,92.000000
9,Tara,9,81.333333
13,Priya,10,88.666667
15,Riya,13,92.666667
17,Aditi,9,82.666667


### Compare Average Marks of Mumbai Students and Pune Students

In [45]:
# Check if 'Pune' exists in the 'city' column
if 'Pune' not in df['city'].unique():
    print("Note: There are no students from 'Pune' in the dataset. Comparing Mumbai students with available cities.")

mumbai_students_avg = df[df['city'] == 'Mumbai']['average_score'].mean()
print(f"Average score of Mumbai students: {mumbai_students_avg:.2f}")

# You can extend this to compare with other cities present in the dataset
available_cities = df['city'].unique()
other_cities_avg = {}
for city in available_cities:
    if city != 'Mumbai':
        other_cities_avg[city] = df[df['city'] == city]['average_score'].mean()
        print(f"Average score of {city} students: {other_cities_avg[city]:.2f}")


Note: There are no students from 'Pune' in the dataset. Comparing Mumbai students with available cities.
Average score of Mumbai students: 56.20
Average score of Delhi students: 86.80
Average score of Mathura students: 59.07
Average score of Noida students: 83.33


### Create 'performance_level' Column

In [46]:
def assign_performance_level(score):
    if score >= 90:
        return 'Excellent'
    elif score >= 75:
        return 'Good'
    elif score >= 60:
        return 'Average'
    else:
        return 'Poor'

df['performance_level'] = df['average_score'].apply(assign_performance_level)
print("DataFrame with 'performance_level' column added (first 5 rows):")
display(df[['name', 'average_score', 'performance_level']].head())

DataFrame with 'performance_level' column added (first 5 rows):


,name,average_score,performance_level
0,Aarav,77.000000,Good
1,Diya,91.000000,Excellent
2,Kabir,58.000000,Poor
3,Meera,77.333333,Good
4,Rohan,46.333333,Poor


### Save Only Selected Columns to a New CSV

In [47]:
selected_columns = ['student_id', 'name', 'city', 'average_score', 'performance_level', 'final_project_score']
df_selected = df[selected_columns]

output_filename_selected = 'session4_student_summary.csv'
df_selected.to_csv(output_filename_selected, index=False)
print(f"Selected student report saved to {output_filename_selected}")
display(df_selected.head())

Selected student report saved to session4_student_summary.csv


,student_id,name,city,average_score,performance_level,final_project_score
0,101,Aarav,Mumbai,77.000000,Good,82
1,102,Diya,Delhi,91.000000,Excellent,93
2,103,Kabir,Mathura,58.000000,Poor,60
3,104,Meera,Noida,77.333333,Good,78
4,105,Rohan,Mumbai,46.333333,Poor,45
